### ISSUE TITLE
Logging in mapper

### ISSUE THREAD

**Issue by taazza** [ezmobius/nanite#12]
Nanite mapper seems to log all requests to agents as INFO:

[Sun, 15 Nov 2009 01:34:35 -0500] INFO: SEND [result] <d5438d58ea90ae66210e6ab6e4c79820> to TEST_I
[Sun, 15 Nov 2009 01:34:35 -0500] INFO: RECV [result] <d97c4b1ba81a26c9e3943c768c1d2423> from TEST_II

Is there any way to control this? The log files grow like crazy when every request is logged. Not sure if this is a logging issue or the way we are using it.

**Comment by roidrage** [comment]
It is indeed a logging issue. There was a merge that changed the logging in a way that everything would go super-noisy even in log level info. I might change that to only use debug for dumping every request, since it's bothering me as well. It is pretty useful to follow the trail of requests, but I agree that it's not great.

**Comment by taazza** [comment]
Agreed, it would make sense to move it to DEBUG. Any chance of a quick fix? We are looking to move to prod in the next week. Thanks ;)

**Comment by roidrage** [comment]
I'll look into it tomorrow.

**Comment by roidrage** [comment]
Fixed in the main code. Will be in the next gem update.
